export const endpoints = {
  health: '/health',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  accounts: {
    list: '/accounts',
    create: '/accounts',
    detail: (id: string) => `/accounts/${id}`,
    balance: (id: string) => `/accounts/${id}/balance`,
    update: (id: string) => `/accounts/${id}`,
    delete: (id: string) => `/accounts/${id}`,
  },
  categories: {
    list: '/categories',
    create: '/categories',
    tree: '/categories/tree',
    detail: (id: string) => `/categories/${id}`,
    update: (id: string) => `/categories/${id}`,
    delete: (id: string) => `/categories/${id}`,
  },
  transactions: {
    list: '/transactions',
    create: '/transactions',
    detail: (id: string) => `/transactions/${id}`,
    update: (id: string) => `/transactions/${id}`,
    delete: (id: string) => `/transactions/${id}`,
    confirm: (id: string) => `/transactions/${id}/confirm`,
  },
  recurrences: {
    list: '/recurrences',
    create: '/recurrences',
    detail: (id: string) => `/recurrences/${id}`,
    update: (id: string) => `/recurrences/${id}`,
    delete: (id: string) => `/recurrences/${id}`,
    generateAll: '/recurrences/generate',
    generate: (id: string) => `/recurrences/${id}/generate`,
  },
  budgets: {
    list: '/budgets',
    create: '/budgets',
    detail: (id: string) => `/budgets/${id}`,
    progress: (id: string) => `/budgets/${id}/progress`,
    update: (id: string) => `/budgets/${id}`,
    delete: (id: string) => `/budgets/${id}`,
  },
  goals: {
    list: '/goals',
    create: '/goals',
    detail: (id: string) => `/goals/${id}`,
    progress: (id: string) => `/goals/${id}/progress`,
    update: (id: string) => `/goals/${id}`,
    delete: (id: string) => `/goals/${id}`,
    contributions: (id: string) => `/goals/${id}/contributions`,
  },
  reports: {
    monthlySummary: '/reports/monthly-summary',
    categorySpending: '/reports/category-spending',
    balanceEvolution: '/reports/balance-evolution',
    budgetVsActual: '/reports/budget-vs-actual',
  },
} as const